### ISSUE TITLE
The expected response from the Gateway Server isn't documented anywhere

### ISSUE THREAD

**Issue by arzam16** [deku-messaging/Deku-SMS-Android#208]
I didn't find anything about how should the Gateway server reply to Deku SMS. Currently Deku expects to receive *any* valid JSON response from Gateway, IMO it should be documented, for example [here](https://github.com/deku-messaging/Deku-SMS-Android?tab=readme-ov-file#-forward-incoming-messages-to-cloud).

If Gateway responds with anything but JSON then `org.json.JSONException` is thrown. For example my Gateway sends status code 200 and "OK" as response body. This is what gets printed in the log:
```
02-11 22:45:08.989 16716 16896 W System.err: java.util.concurrent.ExecutionException: com.android.volley.ParseError: org.json.JSONException: Value OK of type java.lang.String cannot be converted to JSONObject
02-11 22:45:08.990 16716 16896 W System.err: 	at com.android.volley.toolbox.RequestFuture.doGet(RequestFuture.java:124)
02-11 22:45:08.990 16716 16896 W System.err: 	at com.android.volley.toolbox.RequestFuture.get(RequestFuture.java:97)
02-11 22:45:08.990 16716 16896 W System.err: 	at com.afkanerd.deku.Router.Router.RouterHandler.routeJsonMessages(RouterHandler.java:72)
02-11 22:45:08.990 16716 16896 W System.err: 	at com.afkanerd.deku.Router.Router.RouterWorkManager.doWork(RouterWorkManager.java:31)
02-11 22:45:08.990 16716 16896 W System.err: 	at androidx.work.Worker$1.run(Worker.java:82)
02-11 22:45:08.990 16716 16896 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
02-11 22:45:08.990 16716 16896 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
02-11 22:45:08.990 16716 16896 W System.err: 	at java.lang.Thread.run(Thread.java:923)
02-11 22:45:08.990 16716 16896 W System.err: Caused by: com.android.volley.ParseError: org.json.JSONException: Value OK of type java.lang.String cannot be converted to JSONObject
02-11 22:45:08.990 16716 16896 W System.err: 	at com.android.volley.toolbox.JsonObjectRequest.parseNetworkResponse(JsonObjectRequest.java:103)
02-11 22:45:08.990 16716 16896 W System.err: 	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:144)
02-11 22:45:08.990 16716 16896 W System.err: 	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
02-11 22:45:08.990 16716 16896 W System.err: 	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)
02-11 22:45:08.991 16716 16896 W System.err: Caused by: org.json.JSONException: Value OK of type java.lang.String cannot be converted to JSONObject
02-11 22:45:08.991 16716 16896 W System.err: 	at org.json.JSON.typeMismatch(JSON.java:112)
02-11 22:45:08.991 16716 16896 W System.err: 	at org.json.JSONObject.<init>(JSONObject.java:169)
02-11 22:45:08.991 16716 16896 W System.err: 	at org.json.JSONObject.<init>(JSONObject.java:182)
02-11 22:45:08.991 16716 16896 W System.err: 	at com.android.volley.toolbox.JsonObjectRequest.parseNetworkResponse(JsonObjectRequest.java:98)
02-11 22:45:08.991 16716 16896 W System.err: 	... 3 more
02-11 22:45:08.998 16716 16759 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=removed, tags={ com.afkanerd.deku.Router.Router.RouterWorkManager, RECEIVED_SMS_ROUTING, swob.work.id.removed, swob.work.route.url,https://removed/ } ]
```

Despite the result is still `SUCCESS`, I think having this documented will avoid further confusion.

**Comment by sherlockwisdom** [comment]
I agree, this would be a great PR for anyone who wants to help out

**Comment by sherlockwisdom** [comment]
https://github.com/deku-messaging/Deku-SMS-Android?tab=readme-ov-file#-forward-incoming-messages-to-cloud
