### ISSUE TITLE
Crash after set default SMS app version [36-last]

### ISSUE THREAD

**Issue by rhp7rholype** [deku-messaging/Deku-SMS-Android#214]
I install app from f-droid:
Is good work in all versions lower 36.
But after 36 and to the last version... app crash when I set this app default in SMS...

Reinstall app from zero, and clean data and cache

Logs from AM:
`02-22 23:25:14.821 E/m.afkanerd.dek(25620): Not starting debugger since process cannot load the jdwp agent.
02-22 23:25:14.899 D/WM-WrkMgrInitializer(25620): Initializing WorkManager with default configuration.
02-22 23:25:14.922 D/WM-PackageManagerHelper(25620): Skipping component enablement for androidx.work.impl.background.systemjob.SystemJobService
02-22 23:25:14.923 D/WM-Schedulers(25620): Created SystemJobScheduler and enabled SystemJobService
02-22 23:25:14.984 W/AppLocalesStorageHelper(25620): Reading app Locales : Locales record file not found: androidx.appcompat.app.AppCompatDelegate.application_locales_record_file
02-22 23:25:15.144 I/am_on_create_called(25620): [0,com.afkanerd.deku.DefaultSMS.DefaultCheckActivity,performCreate]
02-22 23:25:15.158 I/am_on_start_called(25620): [0,com.afkanerd.deku.DefaultSMS.DefaultCheckActivity,handleStartActivity]
02-22 23:25:15.201 I/am_on_resume_called(25620): [0,com.afkanerd.deku.DefaultSMS.DefaultCheckActivity,RESUME_ACTIVITY]
02-22 23:25:15.205 I/am_on_top_resumed_gained_called(25620): [0,com.afkanerd.deku.DefaultSMS.DefaultCheckActivity,topStateChangedWhenResumed]
02-22 23:25:15.206 I/am_on_top_resumed_lost_called(25620): [0,com.afkanerd.deku.DefaultSMS.DefaultCheckActivity,topStateChangedWhenResumed]
02-22 23:25:15.208 I/am_on_paused_called(25620): [0,com.afkanerd.deku.DefaultSMS.DefaultCheckActivity,performPause]
02-22 23:25:15.227 W/ActivityThread(25620): handleWindowVisibility: no activity for token android.os.BinderProxy@d09b22d
02-22 23:25:15.331 I/am_on_create_called(25620): [0,com.afkanerd.deku.DefaultSMS.ThreadedConversationsActivity,performCreate]
02-22 23:25:15.376 I/am_on_start_called(25620): [0,com.afkanerd.deku.DefaultSMS.ThreadedConversationsActivity,handleStartActivity]
02-22 23:25:15.400 I/am_on_resume_called(25620): [0,com.afkanerd.deku.DefaultSMS.ThreadedConversationsActivity,RESUME_ACTIVITY]
02-22 23:25:15.402 I/SurfaceFactory(25620): [static] sSurfaceFactory = com.mediatek.view.impl.SurfaceFactoryImpl@3ec0a3a
02-22 23:25:15.412 D/ViewRootImpl[ThreadedConversationsActivity](25620): hardware acceleration = true , fakeHwAccelerated = false, sRendererDisabled = false, forceHwAccelerated = false, sSystemRendererDisabled = false
02-22 23:25:15.420 I/InputTransport(25620): Create ARC handle: 0x750bf2cec0
02-22 23:25:15.420 V/PhoneWindow(25620): DecorView setVisiblity: visibility = 0, Parent = android.view.ViewRootImpl@b809006, this = DecorView@c4356c7[ThreadedConversationsActivity]
02-22 23:25:15.421 I/am_on_top_resumed_gained_called(25620): [0,com.afkanerd.deku.DefaultSMS.ThreadedConversationsActivity,topStateChangedWhenResumed]
02-22 23:25:15.474 I/GPUD    (25620): @gpudInitialize: successfully initialized with GL, dbg=0 mmdump_dbg=0 mmpath_dbg=0
02-22 23:25:15.483 E/AndroidRuntime(25620): FATAL EXCEPTION: Thread-3
02-22 23:25:15.483 E/AndroidRuntime(25620): Process: com.afkanerd.deku, PID: 25620
02-22 23:25:15.483 E/AndroidRuntime(25620): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
02-22 23:25:15.483 E/AndroidRuntime(25620): 	at android.os.Parcel.createException(Parcel.java:2077)
02-22 23:25:15.499 I/Process (25620): Sending signal. PID: 25620 SIG: 9
02-22 23:25:15.483 E/AndroidRuntime(25620): 	at android.os.Parcel.readException(Parcel.java:2039)
02-22 23:25:15.499 D/Surface (25620): Surface::connect(this=0x75651e0000,api=1)
02-22 23:25:15.483 E/AndroidRuntime(25620): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:188)
02-22 23:25:15.483 E/AndroidRuntime(25620): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
02-22 23:25:15.483 E/AndroidRuntime(25620): 	at android.content.ContentProviderProxy.query(ContentProviderNative.java:423)
02-22 23:25:15.483 E/AndroidRuntime(25620): 	at android.content.ContentResolver.query(ContentResolver.java:944)
02-22 23:25:15.483 E/AndroidRuntime(25620): 	at android.content.ContentResolver.query(ContentResolver.java:880)
02-22 23:25:15.483 E/AndroidRuntime(25620): 	at android.content.ContentResolver.query(ContentResolver.java:836)
02-22 23:25:15.483 E/AndroidRuntime(25620): 	at com.afkanerd.deku.DefaultSMS.AdaptersViewModels.ThreadedConversationsViewModel$7.run(ThreadedConversationsViewModel.java:231)
02-22 23:25:15.483 E/AndroidRuntime(25620): 	at java.lang.Thread.run(Thread.java:919)`

Device:
Ulefone/Armor_X8/Armor_X8:Android10/SDK29

Thanks

**Comment by sherlockwisdom** [comment]
Please feel free to reopen this issue if persist with 0.41.0
